### ISSUE TITLE
获取选中元素属性并在其他元素内展示

### ISSUE THREAD

**Issue by liandoubuyao** [luckyjxt/jxt_library#1]
@luckyjxt   可查阅jquery手册

**Comment by liandoubuyao** [comment]
@luckyjxt  请先进行切图，然后实现展示元素属性功能

**Comment by liandoubuyao** [comment]
请务必在8月30号下班前完成！

**Comment by luckyjxt** [comment]
请问，你做那了？昨天的多选和更多

**Comment by liandoubuyao** [comment]
![tiaozhuan](https://user-images.githubusercontent.com/17629090/29853829-bd6fd436-8d74-11e7-9be6-eb61d452594e.gif)
更多按钮已完成，正在实现多选功能...

**Comment by luckyjxt** [comment]
蓝朋友好棒！嘿嘿

**Comment by liandoubuyao** [comment]
搜索的多选和更多功能 基本完成！

**Comment by liandoubuyao** [comment]
20170830 半夜
熬夜完成了 选项卡切换延迟关闭模块

**Comment by luckyjxt** [comment]
中国好男友的代表人物
